### ISSUE TITLE
404 points to Launchpad to report bugs, should be github

### ISSUE THREAD

**Issue by deadlight** [ubuntudesign/www.canonical.com#120]
### Current behaviour
http://www.canonical.com/notarealurl gives you the 404 page with a link to Launchpad

### Expected behaviour
The link should be https://github.com/ubuntudesign/www.canonical.com/issues/new

**Comment by barrymcgee** [comment]
Fixed by: https://github.com/ubuntudesign/www.canonical.com/pull/121
