### ISSUE TITLE
Small screen, /projects: the spacing in Explore / Learn more / Learn more section is wrong, missing margin bottom after paragraphs

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.canonical.com#64]

**Comment by deadlight** [comment]
I can't replicate this - it must have been fixed.

If you are still getting this on a particular device/browser, can you please reopen and add a screenshot.

**Comment by yaili** [comment]
I can't replicate it anymore either

No dia 23 de ago de 2016, às 17:53, Karl Williams <notifications@github.com> escreveu:
