### ISSUE TITLE
Careers section of www.canonical.com does not display any jobs

### ISSUE THREAD

**Issue by levonius** [ubuntudesign/www.canonical.com#97]
Hi-
I noticed that when looking at:

http://www.canonical.com/careers/all-vacancies

No jobs are displayed.  When you click "search jobs" you are linked to:

https://ldd.tbe.taleo.net/ldd03/ats/careers/jobSearch.jsp?org=CANONICAL&cws=1&rid=86

Under the header is just the word "null" (see attached screenshot)
![careers](https://cloud.githubusercontent.com/assets/21131622/17822250/08d00294-6624-11e6-8419-fd6db67aa268.png)

Please let me know if I can provide any further details.

Thanks,

-Anthony

**Comment by anthonydillon** [comment]
Hi @levonius thank you very much for taking the time to report this issue. I am seeing 29 vacancies available. This may have been a short outage. Closing this issue but if you experience this issue again please reopen.

**Comment by levonius** [comment]
I am still unable to view jds, but it looks like taleo can confirm that the issue is on their side:

![oracle](https://cloud.githubusercontent.com/assets/21131622/17826678/41c318c6-6641-11e6-9bc8-cabb07881e33.png)

Thanks for having a look.

-Anthony Fappiano
